### ISSUE TITLE
Add to Stackage?

### ISSUE THREAD

**Issue by theGhostJW** [well-typed/falsify#71]
Would be useful to have this package in stackage. Are there any plans to do so?

**Comment by pgujjula** [comment]
Bumping this, this would be really useful for me as well!

**Comment by pgujjula** [comment]
Unfortunately I'll have to stop using this library since it's not on Stackage :/

**Comment by Bodigrim** [comment]
Anyone can add anything to Stackage, it does not have to be a maintainer ;)

**Comment by pgujjula** [comment]
Oh true... if it doesn't get added I'll add it myself in two weeks

**Comment by pgujjula** [comment]
I think the idea isn't that you're taking credit for or control of the package, just that you're the point of contact for Stackage. It would be preferable for the author to add it to Stackage instead of me, so I'm giving them a good chunk of time to respond. @edkso if you want to add yourself, or don't want it added for some reason, please let me know :) And of course if you ever want the Stackage maintainership of falsify transferred to you at any time in the future I will do so.

**Comment by edsko** [comment]
Sorry, I'm just swamped with work, no time for much of anything :/ Yes, by all means, feel free to add it! Thank you :)

**Comment by theGhostJW** [comment]
Looks like you are set to go @pgujjula. Ping me here if you can't get it done and I'll pick it up in the next couple of weeks

**Comment by pgujjula** [comment]
@edsko Thanks! ghc-9.8 needs to be allowed before inclusion into Stackage, can you take a look at https://github.com/well-typed/falsify/pull/72?

**Comment by edsko** [comment]
#72 is now merged :)

**Comment by pgujjula** [comment]
Thank you! Could you republish to Hackage @edsko?

**Comment by edsko** [comment]
Is it sufficient to make a Hackage revision? We've just relaxed some bounds right?

**Comment by edsko** [comment]
I've created the Hackage revision. Let me know if this is insufficient (but I will probably not see that until next week).

**Comment by pgujjula** [comment]
Oh yes, it should be sufficient to create a Hackage revision. Thanks, I'll update shortly.

**Comment by pgujjula** [comment]
Opened a PR to add falsify to Stackage here: https://github.com/commercialhaskell/stackage/pull/7427

**Comment by pgujjula** [comment]
falsify is now added to Stackage! 🙂

**Comment by edsko** [comment]
Very nice, thanks! :)
